production:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID_SW'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY_SW'] %>

test:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID_SW'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY_SW'] %>

development:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID_SW'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY_SW'] %>
